version: '3.4'

services:
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=BrandsCar;Username=postgres;Password=postgres;Pooling=true
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - mynetwork
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: BrandsCar
    ports:
        - "5432:5432"
    volumes:
        - postgres-data:/var/lib/postgresql/data
    networks:
        - mynetwork

networks:
   mynetwork:
     driver: bridge

volumes:
  postgres-data:
          